// Copyright (c) Microsoft Corporation
// License: MIT OR Apache-2.0

//! Direct FFI bindings to NTDDK APIs from the Windows Driver Kit (WDK)
//!
//! This module contains all bindings to functions, constants, methods,
//! constructors and destructors in `ntddk.h`. Types are not included in this
//! module, but are available in the top-level `wdk_sys` module.

pub use bindings::*;

#[allow(missing_docs)]
#[allow(clippy::derive_partial_eq_without_eq)]
mod bindings {
    #[allow(
        clippy::wildcard_imports,
        reason = "the underlying c code relies on all type definitions being in scope, which \
                  results in the bindgen generated code relying on the generated types being in \
                  scope as well"
    )]
    use crate::types::*;

    include!(concat!(env!("OUT_DIR"), "/ntddk.rs"));
}

// MDL (Memory Descriptor List) functions from wdm.h
//
// These functions are defined in wdm.h but not generated by bindgen, either because
// they are inline functions or have attributes that bindgen skips. They are essential
// for safely accessing user-mode memory from kernel-mode.
//
// SAFETY: These functions follow the standard Windows DDK conventions. Callers must
// ensure they follow the documented usage patterns (e.g., unlock MDLs before freeing).
unsafe extern "C" {
    /// Allocates an MDL large enough to describe the specified virtual address range.
    ///
    /// # Parameters
    /// * `VirtualAddress` - Base virtual address to describe
    /// * `Length` - Length of the buffer in bytes
    /// * `SecondaryBuffer` - TRUE if this MDL is for a secondary buffer
    /// * `ChargeQuota` - TRUE to charge quota against the current process
    /// * `Irp` - Optional IRP to associate with the MDL
    ///
    /// # Returns
    /// Pointer to the allocated MDL, or NULL if allocation failed
    ///
    /// # Safety
    /// The caller must free the MDL with `IoFreeMdl` when done.
    pub fn IoAllocateMdl(
        VirtualAddress: crate::types::PVOID,
        Length: crate::types::ULONG,
        SecondaryBuffer: crate::types::BOOLEAN,
        ChargeQuota: crate::types::BOOLEAN,
        Irp: *mut crate::types::IRP,
    ) -> crate::types::PMDL;

    /// Probes pages described by an MDL for accessibility and locks them in memory.
    ///
    /// # Parameters
    /// * `MemoryDescriptorList` - Pointer to the MDL describing the buffer
    /// * `AccessMode` - KernelMode or UserMode
    /// * `Operation` - IoReadAccess, IoWriteAccess, or IoModifyAccess
    ///
    /// # Safety
    /// - Can raise STATUS_ACCESS_VIOLATION if the buffer is invalid
    /// - Must be called at IRQL <= APC_LEVEL
    /// - Must call `MmUnlockPages` before freeing the MDL
    /// - Caller should wrap in __try/__except to handle exceptions
    pub fn MmProbeAndLockPages(
        MemoryDescriptorList: crate::types::PMDL,
        AccessMode: crate::types::KPROCESSOR_MODE,
        Operation: crate::types::LOCK_OPERATION,
    );

    /// Unlocks pages that were locked by `MmProbeAndLockPages`.
    ///
    /// # Parameters
    /// * `MemoryDescriptorList` - Pointer to the MDL describing the locked pages
    ///
    /// # Safety
    /// - Must be called before freeing the MDL
    /// - The MDL must have been locked with `MmProbeAndLockPages`
    pub fn MmUnlockPages(MemoryDescriptorList: crate::types::PMDL);

    /// Frees an MDL allocated by `IoAllocateMdl`.
    ///
    /// # Parameters
    /// * `Mdl` - Pointer to the MDL to free
    ///
    /// # Safety
    /// - Must unlock pages with `MmUnlockPages` before calling this
    /// - The MDL must have been allocated with `IoAllocateMdl`
    pub fn IoFreeMdl(Mdl: crate::types::PMDL);

    /// Returns a nonpaged system-space virtual address for the buffer described by the MDL.
    ///
    /// # Parameters
    /// * `Mdl` - Pointer to the MDL
    /// * `Priority` - MM_PAGE_PRIORITY value (NormalPagePriority = 16)
    ///
    /// # Returns
    /// System virtual address, or NULL if mapping failed
    ///
    /// # Safety
    /// - The MDL must have been locked with `MmProbeAndLockPages`
    /// - This is actually a macro in wdm.h, but we expose it as a function
    pub fn MmGetSystemAddressForMdlSafe(
        Mdl: crate::types::PMDL,
        Priority: crate::types::ULONG,
    ) -> crate::types::PVOID;
}
