// Copyright (c) Microsoft Corporation
// License: MIT OR Apache-2.0

//! Direct FFI bindings to NTDDK APIs from the Windows Driver Kit (WDK)
//!
//! This module contains all bindings to functions, constants, methods,
//! constructors and destructors in `ntddk.h`. Types are not included in this
//! module, but are available in the top-level `wdk_sys` module.

pub use bindings::*;

#[allow(missing_docs)]
#[allow(clippy::derive_partial_eq_without_eq)]
mod bindings {
    #[allow(
        clippy::wildcard_imports,
        reason = "the underlying c code relies on all type definitions being in scope, which \
                  results in the bindgen generated code relying on the generated types being in \
                  scope as well"
    )]
    use crate::types::*;

    include!(concat!(env!("OUT_DIR"), "/ntddk.rs"));
}

// `ExAllocateFromLookasideListEx` and `ExFreeToLookasideListEx` are supplied by
// hand rather than by bindgen, because binding them as plain externs raises
// every consumer's minimum OS to Windows 11 22H2. `build.rs` blocklists them
// from the generated `ntddk.rs`; the module documentation has the mechanism.
mod lookaside_downlevel;
pub use lookaside_downlevel::{ExAllocateFromLookasideListEx, ExFreeToLookasideListEx};

// MDL flag constants for interpreting MDL.MdlFlags
// These are #define macros in wdm.h that bindgen cannot capture
/// The MDL has been mapped into system virtual address space.
pub const MDL_MAPPED_TO_SYSTEM_VA: u16 = 0x0001;
/// The buffer described by the MDL is in nonpaged pool.
pub const MDL_SOURCE_IS_NONPAGED_POOL: u16 = 0x0004;

// MDL (Memory Descriptor List) functions from wdm.h
//
// These functions are defined in wdm.h but not generated by bindgen, either
// because they are inline functions or have attributes that bindgen skips. They
// are essential for safely accessing user-mode memory from kernel-mode.
//
// SAFETY: These functions follow the standard Windows DDK conventions. Callers
// must ensure they follow the documented usage patterns (e.g., unlock MDLs
// before freeing).
unsafe extern "C" {
    /// Allocates an MDL large enough to describe the specified virtual address
    /// range.
    ///
    /// # Parameters
    /// * `VirtualAddress` - Base virtual address to describe
    /// * `Length` - Length of the buffer in bytes
    /// * `SecondaryBuffer` - TRUE if this MDL is for a secondary buffer
    /// * `ChargeQuota` - TRUE to charge quota against the current process
    /// * `Irp` - Optional IRP to associate with the MDL
    ///
    /// # Returns
    /// Pointer to the allocated MDL, or NULL if allocation failed
    ///
    /// # Safety
    /// The caller must free the MDL with `IoFreeMdl` when done.
    pub fn IoAllocateMdl(
        VirtualAddress: crate::types::PVOID,
        Length: crate::types::ULONG,
        SecondaryBuffer: crate::types::BOOLEAN,
        ChargeQuota: crate::types::BOOLEAN,
        Irp: *mut crate::types::IRP,
    ) -> crate::types::PMDL;

    /// Probes pages described by an MDL for accessibility and locks them in
    /// memory.
    ///
    /// # Parameters
    /// * `MemoryDescriptorList` - Pointer to the MDL describing the buffer
    /// * `AccessMode` - KernelMode or UserMode
    /// * `Operation` - IoReadAccess, IoWriteAccess, or IoModifyAccess
    ///
    /// # Safety
    /// - Can raise STATUS_ACCESS_VIOLATION if the buffer is invalid
    /// - Must be called at IRQL <= APC_LEVEL
    /// - Must call `MmUnlockPages` before freeing the MDL
    /// - Caller should wrap in __try/__except to handle exceptions
    pub fn MmProbeAndLockPages(
        MemoryDescriptorList: crate::types::PMDL,
        AccessMode: crate::types::KPROCESSOR_MODE,
        Operation: crate::types::LOCK_OPERATION,
    );

    /// Unlocks pages that were locked by `MmProbeAndLockPages`.
    ///
    /// # Parameters
    /// * `MemoryDescriptorList` - Pointer to the MDL describing the locked
    ///   pages
    ///
    /// # Safety
    /// - Must be called before freeing the MDL
    /// - The MDL must have been locked with `MmProbeAndLockPages`
    pub fn MmUnlockPages(MemoryDescriptorList: crate::types::PMDL);

    /// Frees an MDL allocated by `IoAllocateMdl`.
    ///
    /// # Parameters
    /// * `Mdl` - Pointer to the MDL to free
    ///
    /// # Safety
    /// - Must unlock pages with `MmUnlockPages` before calling this
    /// - The MDL must have been allocated with `IoAllocateMdl`
    pub fn IoFreeMdl(Mdl: crate::types::PMDL);

    /// Maps locked pages described by an MDL into system space.
    ///
    /// # Parameters
    /// * `MemoryDescriptorList` - Pointer to the MDL describing the locked
    ///   pages
    /// * `AccessMode` - `KernelMode` (**0**) or `UserMode` (**1**), matching
    ///   the generated `_MODE` constants. This line previously said "KernelMode
    ///   (1) or UserMode (0)", which is inverted, and a consumer trusted it: it
    ///   passed a literal `1i8` under the comment `// KernelMode`, which maps
    ///   the locked pages into the calling process's *user* address space and
    ///   returns a user VA that the caller then read as a kernel pointer. Pass
    ///   `_MODE::KernelMode` rather than a literal, so the compiler carries the
    ///   meaning instead of a comment.
    /// * `CacheType` - Caching type (MmCached = 1, MmNonCached = 0, etc.)
    /// * `BaseAddress` - Preferred base address (usually NULL)
    /// * `BugCheckOnFailure` - TRUE to bugcheck if mapping fails
    /// * `Priority` - MM_PAGE_PRIORITY value (e.g., NormalPagePriority = 16)
    ///
    /// # Returns
    /// System virtual address of the mapped pages, or NULL if mapping failed
    ///
    /// # Safety
    /// - The MDL must have been locked with `MmProbeAndLockPages`
    /// - If BugCheckOnFailure is TRUE, the function will never return NULL (it
    ///   bugchecks)
    pub fn MmMapLockedPagesSpecifyCache(
        MemoryDescriptorList: crate::types::PMDL,
        AccessMode: crate::types::KPROCESSOR_MODE,
        CacheType: crate::types::MEMORY_CACHING_TYPE,
        BaseAddress: crate::types::PVOID,
        BugCheckOnFailure: crate::types::ULONG,
        Priority: crate::types::ULONG,
    ) -> crate::types::PVOID;

    // Registry functions from ntddk.h
}

// Registry value type constants for ZwSetValueKey
// These are #define macros in winnt.h that bindgen cannot capture
/// No value type.
pub const REG_NONE: u32 = 0;
/// Unicode string.
pub const REG_SZ: u32 = 1;
/// Unicode string with environment variables.
pub const REG_EXPAND_SZ: u32 = 2;
/// Binary data.
pub const REG_BINARY: u32 = 3;
/// 32-bit number.
pub const REG_DWORD: u32 = 4;
/// 32-bit number in big-endian format.
pub const REG_DWORD_BIG_ENDIAN: u32 = 5;
/// Symbolic link.
pub const REG_LINK: u32 = 6;
/// Multiple Unicode strings.
pub const REG_MULTI_SZ: u32 = 7;
/// Resource list.
pub const REG_RESOURCE_LIST: u32 = 8;
/// Full resource descriptor.
pub const REG_FULL_RESOURCE_DESCRIPTOR: u32 = 9;
/// Resource requirements list.
pub const REG_RESOURCE_REQUIREMENTS_LIST: u32 = 10;
/// 64-bit number.
pub const REG_QWORD: u32 = 11;

unsafe extern "C" {
    /// Opens an existing registry key.
    ///
    /// # Parameters
    /// * `KeyHandle` - Pointer to receive the opened key handle
    /// * `DesiredAccess` - ACCESS_MASK specifying desired access rights
    /// * `ObjectAttributes` - Pointer to OBJECT_ATTRIBUTES structure
    ///
    /// # Returns
    /// STATUS_SUCCESS or appropriate error code
    ///
    /// # Safety
    /// - Must call ZwClose on the handle when done
    /// - ObjectAttributes must point to valid, initialized structure
    pub fn ZwOpenKey(
        KeyHandle: *mut crate::types::HANDLE,
        DesiredAccess: crate::types::ACCESS_MASK,
        ObjectAttributes: *mut crate::types::OBJECT_ATTRIBUTES,
    ) -> crate::types::NTSTATUS;

    /// Queries a value entry for a registry key.
    ///
    /// # Parameters
    /// * `KeyHandle` - Handle to the registry key
    /// * `ValueName` - Pointer to UNICODE_STRING with value name
    /// * `KeyValueInformationClass` - Type of information to return
    /// * `KeyValueInformation` - Buffer to receive the value data
    /// * `Length` - Size of the buffer in bytes
    /// * `ResultLength` - Pointer to receive required buffer size
    ///
    /// # Returns
    /// STATUS_SUCCESS or appropriate error code (STATUS_BUFFER_TOO_SMALL if
    /// buffer too small)
    ///
    /// # Safety
    /// - KeyHandle must be a valid open registry key handle
    /// - ValueName must point to valid UNICODE_STRING
    /// - Buffer must be at least Length bytes
    pub fn ZwQueryValueKey(
        KeyHandle: crate::types::HANDLE,
        ValueName: *mut crate::types::UNICODE_STRING,
        KeyValueInformationClass: crate::types::KEY_VALUE_INFORMATION_CLASS,
        KeyValueInformation: crate::types::PVOID,
        Length: crate::types::ULONG,
        ResultLength: *mut crate::types::ULONG,
    ) -> crate::types::NTSTATUS;

    /// Sets a value entry for a registry key.
    ///
    /// # Parameters
    /// * `KeyHandle` - Handle to the registry key
    /// * `ValueName` - Pointer to UNICODE_STRING with value name
    /// * `TitleIndex` - Reserved, must be 0
    /// * `Type` - REG_* type constant (REG_BINARY, REG_DWORD, etc.)
    /// * `Data` - Pointer to the value data
    /// * `DataSize` - Size of the data in bytes
    ///
    /// # Returns
    /// STATUS_SUCCESS or appropriate error code
    ///
    /// # Safety
    /// - KeyHandle must be a valid open registry key handle with KEY_SET_VALUE
    ///   access
    /// - ValueName must point to valid UNICODE_STRING
    /// - Data must point to at least DataSize bytes
    pub fn ZwSetValueKey(
        KeyHandle: crate::types::HANDLE,
        ValueName: *mut crate::types::UNICODE_STRING,
        TitleIndex: crate::types::ULONG,
        Type: crate::types::ULONG,
        Data: crate::types::PVOID,
        DataSize: crate::types::ULONG,
    ) -> crate::types::NTSTATUS;

    /// Closes an object handle.
    ///
    /// # Parameters
    /// * `Handle` - Handle to close (can be registry key, file, etc.)
    ///
    /// # Returns
    /// STATUS_SUCCESS or appropriate error code
    ///
    /// # Safety
    /// - Handle must be a valid open handle
    /// - Do not use the handle after closing it
    pub fn ZwClose(Handle: crate::types::HANDLE) -> crate::types::NTSTATUS;

    /// Returns a pointer to the IMAGE_NT_HEADERS structure for a mapped image.
    ///
    /// # Parameters
    /// * `Base` - Base address of the mapped PE image
    ///
    /// # Returns
    /// Pointer to IMAGE_NT_HEADERS64 if the image is valid, null otherwise
    ///
    /// # Safety
    /// - Base must point to a valid mapped PE image
    /// - The image must remain mapped for the duration of header access
    pub fn RtlImageNtHeader(Base: crate::types::PVOID) -> crate::types::PIMAGE_NT_HEADERS64;

    /// Creates or opens a file, specifying a device object hint.
    ///
    /// Port of `IoCreateFileSpecifyDeviceObjectHint` from ntddk.h.
    ///
    /// # Parameters
    /// * `FileHandle` - Receives the file handle on success
    /// * `DesiredAccess` - ACCESS_MASK specifying desired access rights (e.g., 0 for no access)
    /// * `ObjectAttributes` - Pointer to OBJECT_ATTRIBUTES describing the file
    /// * `IoStatusBlock` - Pointer to IO_STATUS_BLOCK to receive I/O status
    /// * `AllocationSize` - Optional initial allocation size (can be null)
    /// * `FileAttributes` - File attributes (e.g., FILE_ATTRIBUTE_NORMAL = 0x80)
    /// * `ShareAccess` - Sharing mode (FILE_SHARE_READ | FILE_SHARE_WRITE | FILE_SHARE_DELETE)
    /// * `Disposition` - Action to take (FILE_OPEN, FILE_CREATE, etc.)
    /// * `CreateOptions` - Additional options (FILE_OPEN_REPARSE_POINT, etc.)
    /// * `EaBuffer` - Optional extended attributes buffer
    /// * `EaLength` - Length of EaBuffer in bytes
    /// * `CreateFileType` - Type of file to create (CreateFileTypeNone = 0)
    /// * `InternalParameters` - Type-specific parameters (usually null)
    /// * `Options` - IO_IGNORE_SHARE_ACCESS_CHECK or other options
    /// * `DeviceObject` - Optional device object hint
    ///
    /// # Returns
    /// STATUS_SUCCESS or appropriate error code
    ///
    /// # Safety
    /// - FileHandle, ObjectAttributes, and IoStatusBlock must be valid pointers
    /// - Must call ZwClose on the handle when done
    /// - Device object must remain valid if provided
    pub fn IoCreateFileSpecifyDeviceObjectHint(
        FileHandle: *mut crate::types::HANDLE,
        DesiredAccess: crate::types::ACCESS_MASK,
        ObjectAttributes: *mut crate::types::OBJECT_ATTRIBUTES,
        IoStatusBlock: *mut crate::types::IO_STATUS_BLOCK,
        AllocationSize: *mut crate::types::LARGE_INTEGER,
        FileAttributes: crate::types::ULONG,
        ShareAccess: crate::types::ULONG,
        Disposition: crate::types::ULONG,
        CreateOptions: crate::types::ULONG,
        EaBuffer: crate::types::PVOID,
        EaLength: crate::types::ULONG,
        CreateFileType: crate::types::CREATE_FILE_TYPE,
        InternalParameters: crate::types::PVOID,
        Options: crate::types::ULONG,
        DeviceObject: crate::types::PVOID,
    ) -> crate::types::NTSTATUS;

    /// Queries information about a file object.
    ///
    /// Port of `ZwQueryInformationFile` from ntddk.h.
    ///
    /// # Parameters
    /// * `FileHandle` - Handle to the file object
    /// * `IoStatusBlock` - Pointer to IO_STATUS_BLOCK to receive I/O status
    /// * `FileInformation` - Buffer to receive file information
    /// * `Length` - Size of FileInformation buffer in bytes
    /// * `FileInformationClass` - Type of information to query (e.g., FileAlternateNameInformation)
    ///
    /// # Returns
    /// STATUS_SUCCESS or appropriate error code:
    /// - STATUS_OBJECT_NAME_NOT_FOUND if no alternate name exists
    /// - STATUS_NOT_SUPPORTED if the file system doesn't support the query
    ///
    /// # Safety
    /// - FileHandle must be a valid open file handle
    /// - FileInformation buffer must be at least Length bytes
    /// - IoStatusBlock must be a valid pointer
    pub fn ZwQueryInformationFile(
        FileHandle: crate::types::HANDLE,
        IoStatusBlock: *mut crate::types::IO_STATUS_BLOCK,
        FileInformation: crate::types::PVOID,
        Length: crate::types::ULONG,
        FileInformationClass: crate::types::FILE_INFORMATION_CLASS,
    ) -> crate::types::NTSTATUS;
}
